### ISSUE TITLE
compose-rhcs.sh not compatible with python > 3.5

### ISSUE THREAD

**Issue by guits** [ceph/ceph-container#1182]
Looks like compose-rhcs.sh isn't compatible with python >3.5 :

```
$ bash contrib/compose-rhcs.sh
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "maint-lib/stage.py", line 5, in <module>
    import logging
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
make: *** [stage.x86_64,luminous,rhel7,7-released] Error 1
FATAL ERROR !
########################################################
Cannot build rhel7
########################################################
```

running with python <=3.5 fixed this error.

**Comment by dsavineau** [comment]
I tried with python 3.7 (3.7.1) and I don't have the issue.
However it doesn't work with python 3.6 (3.6.7)

```console
Traceback (most recent call last):
  File "maint-lib/stage.py", line 116, in <module>
    main(CORE_FILES_DIR, CEPH_RELEASES_DIR)
  File "maint-lib/stage.py", line 107, in main
    do_variable_replace(replace_root_dir=os.path.join(STAGING_DIR, image))
  File "/root/ceph-container/maint-lib/stagelib/replace.py", line 131, in do_variable_replace
    total_replacements, rendered_text = _do_replace_on_file(file_path, replace_root_dir)
  File "/root/ceph-container/maint-lib/stagelib/replace.py", line 89, in _do_replace_on_file
    rendered_text = _get_file_text(file_path)
  File "/root/ceph-container/maint-lib/stagelib/replace.py", line 26, in _get_file_text
    return txtfile.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 11506: ordinal not in range(128)
Makefile:59: recipe for target 'stage.x86_64,nautilus,ubi8,8-released' failed
make: *** [stage.x86_64,nautilus,ubi8,8-released] Error 1
FATAL ERROR !
```
